#include <QtTest>

#include "css/Style.h"
#include "html/Parser.h"
#include "renderer/BoxTree.h"
#include "renderer/Layout.h"
#include "renderer/Painter.h"

using namespace oqb;

/// Tests for box tree construction, layout and painting.
class LayoutTest : public QObject
{
    Q_OBJECT

private:
    /// Parses, styles and lays out `html` at the given viewport and keeps the
    /// intermediate objects alive for the duration of the calling test.
    struct Page
    {
        html::ParseResult parsed;
        css::StyleEngine engine;
        std::unique_ptr<renderer::Box> boxTree;
        std::unique_ptr<renderer::LayoutEngine> layout;
        renderer::LayoutResult result;

        explicit Page(const QString &html, double width = 800, double height = 600)
            : parsed(html::Parser::parse(html))
            , engine(css::StyleContext{width, height, 16, false})
        {
            for (auto *styleElement : parsed.document->getElementsByTagName(QStringLiteral("style")))
                engine.addStylesheet(css::Stylesheet::parse(styleElement->textContent()));
            engine.computeStyles(parsed.document.get());

            renderer::BoxTreeBuilder::setStyleEngine(&engine);
            boxTree = renderer::BoxTreeBuilder::build(parsed.document.get());

            layout = std::make_unique<renderer::LayoutEngine>();
            layout->setViewport(width, height);
            if (boxTree)
                result = layout->layout(boxTree.get());
        }

        dom::Document *document() const { return parsed.document.get(); }

        /// The box generated by the element with the given id.
        renderer::Box *boxForId(const QString &id) const
        {
            dom::Element *element = document()->getElementById(id);
            return element ? boxForElement(element) : nullptr;
        }

        renderer::Box *boxForElement(dom::Element *element) const
        {
            renderer::Box *found = nullptr;
            std::function<void(renderer::Box *)> walk = [&](renderer::Box *box) {
                if (box->node() == element)
                    found = box;
                for (const auto &child : box->children())
                    walk(child.get());
            };
            if (boxTree)
                walk(boxTree.get());
            return found;
        }
    };

private slots:
    void buildsBoxesForElements();
    void skipsDisplayNone();
    void createsAnonymousBlocks();
    void laysOutBlockStack();
    void appliesPaddingAndBorder();
    void respectsSpecifiedWidth();
    void resolvesPercentageWidth();
    void centresWithAutoMargins();

    // Flexbox.
    void laysFlexItemsInARow();
    void flexGrowSharesFreeSpace();
    void flexShrinkTakesSpaceBack();
    void honoursJustifyContent_data();
    void honoursJustifyContent();
    void honoursAlignItems_data();
    void honoursAlignItems();
    void stretchesItemsByDefault();
    void laysFlexColumn();
    void reversesRowDirection();
    void wrapsItemsOntoLines();
    void honoursFlexGap();
    void appliesOrder();
    void handlesFlexBasis();
    void keepsFlexItemsOutOfTheAnonymousBox();
    void handlesNestedFlexContainers();
    void honoursBoxSizing();

    // Positioning.
    void movesRelativelyPositionedBoxes();
    void laysOutAbsolutelyPositionedBoxes();
    void pinsAbsoluteBoxesToTheFarEdges();
    void fillsBetweenOppositeOffsets();
    void stretchesAnAbsoluteBoxBetweenTopAndBottom();
    void positionsAgainstTheNearestPositionedAncestor();
    void keepsOutOfFlowBoxesOutOfFlow();
    void laysOutContentInsideAnAbsoluteBox();
    void paintsStickyBoxesAtTheViewportEdge();
    void paintsPositiveZIndexOnTop();
    void collapsesAdjacentMargins();
    void wrapsLongTextIntoLines();
    void laysOutInlineElements();
    void honoursLineHeight();
    void positionsListMarkers();
    void sizesReplacedElements();
    void growsDocumentHeightWithContent();
    void paintsBackgroundColours();
    void paintsTextPixels();
    void cullsOffscreenContent();
};

void LayoutTest::buildsBoxesForElements()
{
    Page page(QStringLiteral("<body><div id=\"a\">x</div></body>"));

    QVERIFY(page.boxTree != nullptr);
    renderer::Box *box = page.boxForId(QStringLiteral("a"));
    QVERIFY(box != nullptr);
    QCOMPARE(box->type(), renderer::Box::Type::Block);
    QVERIFY(box->width() > 0);
}

void LayoutTest::skipsDisplayNone()
{
    Page page(QStringLiteral(
        "<body><style>.gone { display: none }</style>"
        "<div id=\"a\">shown</div><div id=\"b\" class=\"gone\">hidden</div></body>"));

    QVERIFY(page.boxForId(QStringLiteral("a")) != nullptr);
    QVERIFY(page.boxForId(QStringLiteral("b")) == nullptr);
}

void LayoutTest::createsAnonymousBlocks()
{
    // Inline content between blocks is wrapped so a block container never mixes
    // block and inline children directly.
    Page page(QStringLiteral("<body><div id=\"a\">text<p>block</p>more</div></body>"));

    renderer::Box *box = page.boxForId(QStringLiteral("a"));
    QVERIFY(box != nullptr);
    QVERIFY(box->childCount() >= 2);

    bool sawAnonymous = false;
    for (const auto &child : box->children()) {
        if (child->type() == renderer::Box::Type::Anonymous)
            sawAnonymous = true;
    }
    QVERIFY(sawAnonymous);
}

void LayoutTest::laysOutBlockStack()
{
    Page page(QStringLiteral(
        "<body><div id=\"a\">one</div><div id=\"b\">two</div><div id=\"c\">three</div></body>"));

    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    renderer::Box *c = page.boxForId(QStringLiteral("c"));

    QVERIFY(a && b && c);
    // Blocks stack: each starts below the previous one.
    QVERIFY(b->y() >= a->y() + a->height());
    QVERIFY(c->y() >= b->y() + b->height());
    // None overflows the viewport width.
    QVERIFY(a->width() <= 800);
    QCOMPARE(a->width(), 800 - 16); // body has an 8px margin on each side
}

void LayoutTest::appliesPaddingAndBorder()
{
    Page page(QStringLiteral(
        "<body><style>#a { padding: 10px 20px; border: 3px solid black; width: 100px }</style>"
        "<div id=\"a\">x</div></body>"));

    renderer::Box *box = page.boxForId(QStringLiteral("a"));
    QVERIFY(box != nullptr);

    // The border box is the content plus padding plus border on both axes.
    QCOMPARE(box->width(), 100.0 + 40.0 + 6.0);
    QVERIFY(box->height() >= 30.0);
    QCOMPARE(box->contentBox().width(), 100.0);
}

void LayoutTest::respectsSpecifiedWidth()
{
    Page page(QStringLiteral(
        "<body><style>#a { width: 250px } #b { width: 400px }</style>"
        "<div id=\"a\">x</div><div id=\"b\">y</div></body>"));

    QCOMPARE(page.boxForId(QStringLiteral("a"))->width(), 250.0);
    QCOMPARE(page.boxForId(QStringLiteral("b"))->width(), 400.0);
}

void LayoutTest::resolvesPercentageWidth()
{
    Page page(QStringLiteral(
        "<body><style>#outer { width: 400px } #a { width: 50% }</style>"
        "<div id=\"outer\"><div id=\"a\">x</div></div></body>"));

    // 50% of the containing block's content width, which is 400px.
    QCOMPARE(page.boxForId(QStringLiteral("a"))->width(), 200.0);
}

void LayoutTest::centresWithAutoMargins()
{
    Page page(QStringLiteral(
        "<body><style>#a { width: 200px; margin: 0 auto }</style><div id=\"a\">x</div></body>"));

    renderer::Box *box = page.boxForId(QStringLiteral("a"));
    QVERIFY(box != nullptr);

    // Body content is 784px wide (800 minus two 8px margins), so a 200px box
    // centred inside it starts at 8 + (784 - 200) / 2 = 300.
    QCOMPARE(box->x(), 300.0);
}

void LayoutTest::collapsesAdjacentMargins()
{
    // Two 20px margins between siblings collapse to a single 20px gap, not 40.
    Page page(QStringLiteral(
        "<body><style>body { margin: 0 } "
        "#a { margin-bottom: 20px } #b { margin-top: 20px }</style>"
        "<div id=\"a\">one</div><div id=\"b\">two</div></body>"));

    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));

    QCOMPARE(b->y() - (a->y() + a->height()), 20.0);

    // A larger margin still wins over a smaller one.
    Page larger(QStringLiteral(
        "<body><style>body { margin: 0 } "
        "#a { margin-bottom: 10px } #b { margin-top: 30px }</style>"
        "<div id=\"a\">one</div><div id=\"b\">two</div></body>"));
    renderer::Box *largeA = larger.boxForId(QStringLiteral("a"));
    renderer::Box *largeB = larger.boxForId(QStringLiteral("b"));
    QCOMPARE(largeB->y() - (largeA->y() + largeA->height()), 30.0);
}

void LayoutTest::wrapsLongTextIntoLines()
{
    const QString text = QString(200, u'x');
    Page page(QStringLiteral("<body><style>body { margin: 0 } p { width: 120px }</style><p>%1</p></body>")
                  .arg(text));

    // A long word cannot break, so it overflows rather than disappearing.
    QVERIFY(!page.result.lineBoxes.empty());

    // A long sentence does break, producing several lines.
    Page sentence(QStringLiteral(
        "<body><style>body { margin: 0 } p { width: 200px }</style>"
        "<p>The quick brown fox jumps over the lazy dog and keeps on running for a while.</p></body>"));
    QVERIFY(sentence.result.lineBoxes.size() > 1);

    // Lines stack downwards.
    for (size_t i = 1; i < sentence.result.lineBoxes.size(); ++i) {
        QVERIFY(sentence.result.lineBoxes[i]->y()
                > sentence.result.lineBoxes[i - 1]->y());
    }
}

void LayoutTest::laysOutInlineElements()
{
    Page page(QStringLiteral(
        "<body><style>body { margin: 0 }</style>"
        "<p id=\"p\">plain <b id=\"b\">bold</b> tail</p></body>"));

    renderer::Box *paragraph = page.boxForId(QStringLiteral("p"));
    QVERIFY(paragraph != nullptr);
    QVERIFY(paragraph->width() > 0);

    // The bold text is on the same line as the surrounding text, not below it.
    const double paragraphTop = paragraph->y();
    int linesOnFirstRow = 0;
    for (renderer::Box *line : page.result.lineBoxes) {
        if (line->y() < paragraphTop + 30)
            ++linesOnFirstRow;
    }
    QVERIFY(linesOnFirstRow >= 1);
}

void LayoutTest::honoursLineHeight()
{
    Page page(QStringLiteral(
        "<body><style>body { margin: 0 } p { line-height: 40px }</style>"
        "<p id=\"p\">one line</p></body>"));

    renderer::Box *paragraph = page.boxForId(QStringLiteral("p"));
    QVERIFY(paragraph != nullptr);
    // The single line is 40px tall, so the paragraph is too.
    QCOMPARE(paragraph->height(), 40.0);
}

void LayoutTest::positionsListMarkers()
{
    Page page(QStringLiteral(
        "<body><style>body { margin: 0 }</style><ul id=\"u\"><li id=\"a\">one</li>"
        "<li id=\"b\">two</li></ul></body>"));

    renderer::Box *list = page.boxForId(QStringLiteral("u"));
    QVERIFY(list != nullptr);

    // Each item carries a bullet box with a marker glyph.
    int bullets = 0;
    std::function<void(renderer::Box *)> walk = [&](renderer::Box *box) {
        if (box->type() == renderer::Box::Type::Bullet) {
            ++bullets;
            QVERIFY(!box->text().isEmpty());
        }
        for (const auto &child : box->children())
            walk(child.get());
    };
    walk(list);
    QCOMPARE(bullets, 2);

    // The second item sits below the first.
    renderer::Box *first = page.boxForId(QStringLiteral("a"));
    renderer::Box *second = page.boxForId(QStringLiteral("b"));
    QVERIFY(second->y() >= first->y() + first->height());
}

void LayoutTest::sizesReplacedElements()
{
    Page page(QStringLiteral(
        "<body><style>body { margin: 0 }</style>"
        "<img id=\"i\" src=\"nonexistent.png\" width=\"120\" height=\"80\"></body>"));

    renderer::Box *image = page.boxForId(QStringLiteral("i"));
    QVERIFY(image != nullptr);
    QCOMPARE(image->type(), renderer::Box::Type::Replaced);

    // The width and height attributes are presentational hints, so the replaced
    // box takes exactly those dimensions.
    QCOMPARE(image->width(), 120.0);
    QCOMPARE(image->height(), 80.0);
}

void LayoutTest::growsDocumentHeightWithContent()
{
    Page shortPage(QStringLiteral("<body><p>one</p></body>"));
    Page longPage(QStringLiteral(
        "<body><div style=\"height: 3000px\">tall</div></body>"));

    QVERIFY(longPage.result.documentHeight > shortPage.result.documentHeight);
    QVERIFY(longPage.result.documentHeight >= 3000.0);
    // A page shorter than the viewport still reports the viewport height, so
    // the window background fills correctly.
    QVERIFY(shortPage.result.documentHeight >= 600.0);
}

void LayoutTest::paintsBackgroundColours()
{
    Page page(QStringLiteral(
        "<body><style>body { margin: 0; background: #f5f5f5 } "
        "#a { width: 100px; height: 50px; background: #ff0000 }</style>"
        "<div id=\"a\"></div></body>"));

    const QImage image = renderer::Painter::renderToImage(page.boxTree.get(), 800, 600);
    QVERIFY(!image.isNull());

    renderer::Box *box = page.boxForId(QStringLiteral("a"));
    const int centerX = static_cast<int>(box->x() + box->width() / 2);
    const int centerY = static_cast<int>(box->y() + box->height() / 2);

    QCOMPARE(image.pixelColor(centerX, centerY), QColor(255, 0, 0));
    // Outside the box the body background shows through.
    QCOMPARE(image.pixelColor(500, 300), QColor(245, 245, 245));
}

void LayoutTest::paintsTextPixels()
{
    Page page(QStringLiteral(
        "<body><style>body { margin: 0; background: white; color: black; font-size: 40px }"
        "</style><div>MMMM</div></body>"));

    const QImage image = renderer::Painter::renderToImage(page.boxTree.get(), 400, 200);

    // Large black text on white must produce dark pixels.
    int dark = 0;
    for (int y = 0; y < image.height(); ++y) {
        for (int x = 0; x < image.width(); ++x) {
            if (image.pixelColor(x, y).lightness() < 100)
                ++dark;
        }
    }
    QVERIFY2(dark > 200, qPrintable(QStringLiteral("only %1 dark pixels").arg(dark)));
}

void LayoutTest::cullsOffscreenContent()
{
    // A box far below the viewport must not be painted.
    Page page(QStringLiteral(
        "<body><style>body { margin: 0 } #far { margin-top: 5000px; height: 50px; "
        "background: #00ff00 }</style><div id=\"far\"></div></body>"));

    renderer::Box *box = page.boxForId(QStringLiteral("far"));
    QVERIFY(box != nullptr);
    // A 5000px top margin places the box's border edge exactly 5000px down.
    QCOMPARE(box->y(), 5000.0);
    // The document is tall enough to scroll to it.
    QVERIFY(page.result.documentHeight >= 5050.0);

    const QImage image = renderer::Painter::renderToImage(page.boxTree.get(), 400, 300);

    // No green anywhere in the visible area.
    int green = 0;
    for (int y = 0; y < image.height(); ++y) {
        for (int x = 0; x < image.width(); ++x) {
            const QColor c = image.pixelColor(x, y);
            if (c.green() > 200 && c.red() < 100 && c.blue() < 100)
                ++green;
        }
    }
    QCOMPARE(green, 0);
}

// ------------------------------------------------------------------ flexbox

void LayoutTest::laysFlexItemsInARow()
{
    // A row container places its items side by side, left to right, in document
    // order. Before flexbox existed every one of these stacked vertically.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:600px'>"
        "<div id='a' style='width:100px'>A</div>"
        "<div id='b' style='width:200px'>B</div>"
        "<div id='c' style='width:150px'>C</div>"
        "</div></body></html>"));

    renderer::Box *row = page.boxForId(QStringLiteral("row"));
    QVERIFY(row);
    QCOMPARE(row->width(), 600.0);

    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    renderer::Box *c = page.boxForId(QStringLiteral("c"));
    QVERIFY(a && b && c);

    // The widths are honoured, since nothing grows or shrinks by default beyond
    // the shrink factor that only applies when the line overflows.
    QCOMPARE(a->width(), 100.0);
    QCOMPARE(b->width(), 200.0);
    QCOMPARE(c->width(), 150.0);

    // Each item starts where the previous one ended, and they share one row: a
    // row of items is side by side, so their y positions agree.
    QCOMPARE(a->x(), row->contentBox().x());
    QCOMPARE(b->x(), a->x() + a->width());
    QCOMPARE(c->x(), b->x() + b->width());
    QCOMPARE(a->y(), b->y());
    QCOMPARE(b->y(), c->y());
}

void LayoutTest::flexGrowSharesFreeSpace()
{
    // free space 600 - (100 + 200) = 300, split 1:2 between the two items.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:600px'>"
        "<div id='a' style='flex:1 1 100px'>A</div>"
        "<div id='b' style='flex:2 1 100px'>B</div>"
        "</div></body></html>"));

    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    QVERIFY(a && b);

    // 100 + 100 = 200 used, so 400 is free and shared 1:2.
    QVERIFY(qAbs(a->width() - 233.333333) < 0.01);
    QVERIFY(qAbs(b->width() - 366.666667) < 0.01);

    // The two items fill the row exactly, which is what growing is for.
    QVERIFY(qAbs((a->width() + b->width()) - 600.0) < 0.01);
    QCOMPARE(b->x(), a->x() + a->width());
}

void LayoutTest::flexShrinkTakesSpaceBack()
{
    // Two 400px items in a 600px row have to give up 200px. Shrinking is
    // weighted by the base size, and both are equal, so each gives up half.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:600px'>"
        "<div id='a' style='flex:0 1 400px'>A</div>"
        "<div id='b' style='flex:0 1 400px'>B</div>"
        "</div></body></html>"));

    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    QVERIFY(a && b);

    QCOMPARE(a->width(), 300.0);
    QCOMPARE(b->width(), 300.0);

    // An item that may not shrink keeps its size and overflows instead.
    Page fixed(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:200px'>"
        "<div id='a' style='flex:0 0 400px'>A</div>"
        "</div></body></html>"));

    renderer::Box *wide = fixed.boxForId(QStringLiteral("a"));
    QVERIFY(wide);
    QCOMPARE(wide->width(), 400.0);
}

void LayoutTest::honoursJustifyContent_data()
{
    QTest::addColumn<QString>("justify");
    QTest::addColumn<double>("firstX");
    QTest::addColumn<double>("secondX");

    // Two 100px items in a 500px row leave 300px for justify-content to place.
    QTest::newRow("flex-start") << QStringLiteral("flex-start") << 0.0 << 100.0;
    QTest::newRow("flex-end") << QStringLiteral("flex-end") << 300.0 << 400.0;
    QTest::newRow("center") << QStringLiteral("center") << 150.0 << 250.0;
    QTest::newRow("space-between") << QStringLiteral("space-between") << 0.0 << 400.0;
    QTest::newRow("space-around") << QStringLiteral("space-around") << 75.0 << 325.0;
    QTest::newRow("space-evenly") << QStringLiteral("space-evenly") << 100.0 << 300.0;
}

void LayoutTest::honoursJustifyContent()
{
    QFETCH(QString, justify);
    QFETCH(double, firstX);
    QFETCH(double, secondX);

    Page page(QStringLiteral(
                  "<html><body style='margin:0'>"
                  "<div id='row' style='display:flex; width:500px; justify-content:%1'>"
                  "<div id='a' style='flex:0 0 100px'>A</div>"
                  "<div id='b' style='flex:0 0 100px'>B</div>"
                  "</div></body></html>")
                  .arg(justify));

    renderer::Box *row = page.boxForId(QStringLiteral("row"));
    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    QVERIFY(row && a && b);

    // Positions are relative to the row's content box, which is where flex
    // layout places items.
    const double base = row->contentBox().x();
    QVERIFY2(qAbs((a->x() - base) - firstX) < 0.01,
             qPrintable(QStringLiteral("first item at %1, expected %2")
                            .arg(a->x() - base)
                            .arg(firstX)));
    QVERIFY2(qAbs((b->x() - base) - secondX) < 0.01,
             qPrintable(QStringLiteral("second item at %1, expected %2")
                            .arg(b->x() - base)
                            .arg(secondX)));
}

void LayoutTest::honoursAlignItems_data()
{
    QTest::addColumn<QString>("align");
    QTest::addColumn<double>("expectedY");

    // The tallest item is 100px, and the short one is 20px tall, so the short
    // item's offset within the line is what align-items decides.
    QTest::newRow("flex-start") << QStringLiteral("flex-start") << 0.0;
    QTest::newRow("flex-end") << QStringLiteral("flex-end") << 80.0;
    QTest::newRow("center") << QStringLiteral("center") << 40.0;
}

void LayoutTest::honoursAlignItems()
{
    QFETCH(QString, align);
    QFETCH(double, expectedY);

    Page page(QStringLiteral(
                  "<html><body style='margin:0'>"
                  "<div id='row' style='display:flex; width:400px; align-items:%1'>"
                  "<div id='tall' style='width:100px; height:100px'>T</div>"
                  "<div id='short' style='width:100px; height:20px'>S</div>"
                  "</div></body></html>")
                  .arg(align));

    renderer::Box *row = page.boxForId(QStringLiteral("row"));
    renderer::Box *shortItem = page.boxForId(QStringLiteral("short"));
    QVERIFY(row && shortItem);

    const double base = row->contentBox().y();
    QVERIFY2(qAbs((shortItem->y() - base) - expectedY) < 0.01,
             qPrintable(QStringLiteral("short item at %1, expected %2")
                            .arg(shortItem->y() - base)
                            .arg(expectedY)));
}

void LayoutTest::stretchesItemsByDefault()
{
    // align-items defaults to stretch, so an item with no height fills the line.
    // This is the behaviour that makes equal-height columns work.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:400px'>"
        "<div id='tall' style='width:100px; height:120px'>T</div>"
        "<div id='auto' style='width:100px'>A</div>"
        "</div></body></html>"));

    renderer::Box *tall = page.boxForId(QStringLiteral("tall"));
    renderer::Box *stretched = page.boxForId(QStringLiteral("auto"));
    QVERIFY(tall && stretched);

    QCOMPARE(tall->height(), 120.0);
    QCOMPARE(stretched->height(), 120.0);
    QCOMPARE(stretched->y(), tall->y());
}

void LayoutTest::laysFlexColumn()
{
    // A column container stacks its items, and the main axis becomes vertical.
    // justify-content then moves them down the container instead of across.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='col' style='display:flex; flex-direction:column; width:300px; height:400px;"
        " justify-content:space-between'>"
        "<div id='a' style='height:50px'>A</div>"
        "<div id='b' style='height:50px'>B</div>"
        "</div></body></html>"));

    renderer::Box *col = page.boxForId(QStringLiteral("col"));
    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    QVERIFY(col && a && b);

    // Items stack, and they fill the container's width by default.
    QCOMPARE(a->width(), 300.0);
    QCOMPARE(b->width(), 300.0);

    const double base = col->contentBox().y();
    QCOMPARE(a->y() - base, 0.0);

    // space-between puts the last item flush with the bottom: 400 - 50 = 350.
    QVERIFY2(qAbs((b->y() - base) - 350.0) < 0.01,
             qPrintable(QStringLiteral("last item at %1").arg(b->y() - base)));
}

void LayoutTest::reversesRowDirection()
{
    // row-reverse places the first item on the right, so document order is
    // reversed on the main axis while the items keep their own sizes.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; flex-direction:row-reverse; width:400px'>"
        "<div id='a' style='flex:0 0 100px'>A</div>"
        "<div id='b' style='flex:0 0 100px'>B</div>"
        "</div></body></html>"));

    renderer::Box *row = page.boxForId(QStringLiteral("row"));
    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    QVERIFY(row && a && b);

    const double base = row->contentBox().x();
    // A comes first in the document, so it is placed at the far end.
    QVERIFY2(qAbs((a->x() - base) - 300.0) < 0.01,
             qPrintable(QStringLiteral("first item at %1, expected 300").arg(a->x() - base)));
    QVERIFY2(qAbs((b->x() - base) - 200.0) < 0.01,
             qPrintable(QStringLiteral("second item at %1, expected 200").arg(b->x() - base)));
}

void LayoutTest::wrapsItemsOntoLines()
{
    // Three 100px items in a 250px wrapping row fit two to a line, with the
    // third wrapping to the next.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; flex-wrap:wrap; width:250px'>"
        "<div id='a' style='flex:0 0 100px; height:20px'>A</div>"
        "<div id='b' style='flex:0 0 100px; height:20px'>B</div>"
        "<div id='c' style='flex:0 0 100px; height:20px'>C</div>"
        "</div></body></html>"));

    renderer::Box *row = page.boxForId(QStringLiteral("row"));
    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    renderer::Box *c = page.boxForId(QStringLiteral("c"));
    QVERIFY(row && a && b && c);

    // A and B share the first line, so their y positions agree and they sit
    // side by side.
    QCOMPARE(a->y(), b->y());
    QCOMPARE(b->x(), a->x() + 100.0);

    // C wrapped, so it is below them and back at the start of the line.
    QCOMPARE(c->x(), a->x());
    QVERIFY2(c->y() > b->y(), "the wrapped item should be on a lower line");

    // The container grew to hold both lines.
    QCOMPARE(row->height(), 40.0);

    // Without wrapping the same items stay on one line and overflow.
    Page nowrap(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:250px'>"
        "<div id='a' style='flex:0 0 100px; height:20px'>A</div>"
        "<div id='b' style='flex:0 0 100px; height:20px'>B</div>"
        "<div id='c' style='flex:0 0 100px; height:20px'>C</div>"
        "</div></body></html>"));

    renderer::Box *na = nowrap.boxForId(QStringLiteral("a"));
    renderer::Box *nc = nowrap.boxForId(QStringLiteral("c"));
    QVERIFY(na && nc);
    QCOMPARE(na->y(), nc->y());
    QCOMPARE(nc->x(), na->x() + 200.0);
}

void LayoutTest::honoursFlexGap()
{
    // gap puts space between items and never before the first or after the last,
    // which is the difference between gap and margin.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:500px; gap:20px'>"
        "<div id='a' style='flex:0 0 100px; height:10px'>A</div>"
        "<div id='b' style='flex:0 0 100px; height:10px'>B</div>"
        "<div id='c' style='flex:0 0 100px; height:10px'>C</div>"
        "</div></body></html>"));

    renderer::Box *row = page.boxForId(QStringLiteral("row"));
    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    renderer::Box *c = page.boxForId(QStringLiteral("c"));
    QVERIFY(row && a && b && c);

    const double base = row->contentBox().x();
    QCOMPARE(a->x() - base, 0.0);
    QCOMPARE(b->x() - base, 120.0);
    QCOMPARE(c->x() - base, 240.0);

    // The gaps are accounted for when the free space is computed, so the items
    // keep the size the shorthand gave them and the leftover stays unused. The
    // gaps are what separates them, and none appears before the first or after
    // the last, which is the difference between gap and margin.
    QCOMPARE(a->width(), 100.0);
    QCOMPARE(b->width(), 100.0);
    QCOMPARE(c->width(), 100.0);
    QCOMPARE(a->width() + b->width() + c->width() + 40.0, 340.0);

    // With a grow factor the items do take the leftover, and the gaps are still
    // subtracted from what is distributed.
    Page growing(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:500px; gap:20px'>"
        "<div id='a' style='flex:1 1 100px; height:10px'>A</div>"
        "<div id='b' style='flex:1 1 100px; height:10px'>B</div>"
        "<div id='c' style='flex:1 1 100px; height:10px'>C</div>"
        "</div></body></html>"));

    renderer::Box *ga = growing.boxForId(QStringLiteral("a"));
    QVERIFY(ga);
    // 500 - 300 - 40 = 160 shared equally, so each item becomes 100 + 53.33.
    QVERIFY(qAbs(ga->width() - 153.333333) < 0.01);
}

void LayoutTest::appliesOrder()
{
    // order changes the sequence items are placed in without changing the
    // document, which `order: -1` uses to pull an item to the front.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:400px'>"
        "<div id='a' style='flex:0 0 100px; order:1'>A</div>"
        "<div id='b' style='flex:0 0 100px; order:-1'>B</div>"
        "<div id='c' style='flex:0 0 100px'>C</div>"
        "</div></body></html>"));

    renderer::Box *row = page.boxForId(QStringLiteral("row"));
    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    renderer::Box *c = page.boxForId(QStringLiteral("c"));
    QVERIFY(row && a && b && c);

    const double base = row->contentBox().x();

    // B has the lowest order so it goes first; A has the highest so it last.
    QCOMPARE(b->x() - base, 0.0);
    QCOMPARE(c->x() - base, 100.0);
    QCOMPARE(a->x() - base, 200.0);
}

void LayoutTest::handlesFlexBasis()
{
    // A definite flex-basis wins over the item's width, which is what makes the
    // shorthand usable for equal columns regardless of content.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:300px'>"
        "<div id='a' style='width:10px; flex:0 0 150px'>A</div>"
        "<div id='b' style='width:10px; flex:0 0 150px'>B</div>"
        "</div></body></html>"));

    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    QVERIFY(a && b);

    QCOMPARE(a->width(), 150.0);
    QCOMPARE(b->width(), 150.0);

    // A percentage basis resolves against the container's main size.
    Page percent(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:400px'>"
        "<div id='a' style='flex:0 0 25%'>A</div>"
        "<div id='b' style='flex:0 0 50%'>B</div>"
        "</div></body></html>"));

    QCOMPARE(percent.boxForId(QStringLiteral("a"))->width(), 100.0);
    QCOMPARE(percent.boxForId(QStringLiteral("b"))->width(), 200.0);
}

void LayoutTest::keepsFlexItemsOutOfTheAnonymousBox()
{
    // A flex container must not wrap its inline children in an anonymous block:
    // each child is an item of its own. Wrapping them made the whole run one
    // item, so justify-content had nothing to distribute between.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='row' style='display:flex; width:400px; justify-content:space-between'>"
        "<span id='a'>A</span><span id='b'>B</span>"
        "</div></body></html>"));

    renderer::Box *row = page.boxForId(QStringLiteral("row"));
    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    QVERIFY(row && a && b);

    // Two spans are two items, so space-between separates them across the row.
    const double base = row->contentBox().x();
    QCOMPARE(a->x() - base, 0.0);
    QVERIFY2(b->x() > a->x() + 300.0,
             qPrintable(QStringLiteral("second span at %1").arg(b->x() - base)));

    // The container has exactly two children, which is what proves no anonymous
    // wrapper was inserted.
    QCOMPARE(row->childCount(), 2);
}

void LayoutTest::handlesNestedFlexContainers()
{
    // A flex item may itself be a flex container, which is the outer-shell
    // pattern every page uses.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='outer' style='display:flex; width:600px'>"
        "<div id='sidebar' style='flex:0 0 200px'></div>"
        "<div id='main' style='flex:1; display:flex; gap:10px'>"
        "<div id='x' style='flex:1'>X</div>"
        "<div id='y' style='flex:1'>Y</div>"
        "</div>"
        "</div></body></html>"));

    renderer::Box *outer = page.boxForId(QStringLiteral("outer"));
    renderer::Box *sidebar = page.boxForId(QStringLiteral("sidebar"));
    renderer::Box *main = page.boxForId(QStringLiteral("main"));
    renderer::Box *x = page.boxForId(QStringLiteral("x"));
    renderer::Box *y = page.boxForId(QStringLiteral("y"));
    QVERIFY(outer && sidebar && main && x && y);

    QCOMPARE(sidebar->width(), 200.0);
    QCOMPARE(main->width(), 400.0);

    // The inner row splits its 400px between two items with a 10px gap.
    QCOMPARE(x->width(), 195.0);
    QCOMPARE(y->width(), 195.0);
    QCOMPARE(y->x(), x->x() + 195.0 + 10.0);
}

void LayoutTest::honoursBoxSizing()
{
    // content-box is the initial value: the specified width is the content, and
    // padding and border are added outside it.
    Page contentBox(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='a' style='width:100px; padding:10px; border:5px solid black'>x</div>"
        "</body></html>"));

    renderer::Box *plain = contentBox.boxForId(QStringLiteral("a"));
    QVERIFY(plain);
    QCOMPARE(plain->width(), 130.0); // 100 + 2*10 padding + 2*5 border

    // border-box makes the specified width the whole border box, which is what
    // `* { box-sizing: border-box }` asks for and what nearly every modern
    // stylesheet sets.
    Page borderBox(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='a' style='box-sizing:border-box; width:100px; padding:10px;"
        " border:5px solid black'>x</div>"
        "</body></html>"));

    renderer::Box *sized = borderBox.boxForId(QStringLiteral("a"));
    QVERIFY(sized);
    QCOMPARE(sized->width(), 100.0);
    // The content box is what is left, which is what the padding and border are
    // taken out of.
    QCOMPARE(sized->contentBox().width(), 70.0);

    // A percentage of the containing block follows the same rule.
    Page percentage(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div style='width:200px'>"
        "<div id='a' style='box-sizing:border-box; width:50%; padding:10px'>x</div>"
        "</div></body></html>"));

    renderer::Box *half = percentage.boxForId(QStringLiteral("a"));
    QVERIFY(half);
    QCOMPARE(half->width(), 100.0);
    QCOMPARE(half->contentBox().width(), 80.0);

    // The height follows the same rule.
    Page heights(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='a' style='box-sizing:border-box; height:60px; padding:10px'>x</div>"
        "</body></html>"));

    renderer::Box *boxed = heights.boxForId(QStringLiteral("a"));
    QVERIFY(boxed);
    QCOMPARE(boxed->height(), 60.0);

    // A flex item with a basis and padding is a border box too, which is what
    // stops a padded card from overflowing its row.
    Page flex(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div style='display:flex; box-sizing:border-box; width:300px'>"
        "<div id='a' style='box-sizing:border-box; flex:1 1 100px; padding:10px'>A</div>"
        "<div id='b' style='box-sizing:border-box; flex:1 1 100px; padding:10px'>B</div>"
        "</div></body></html>"));

    renderer::Box *fa = flex.boxForId(QStringLiteral("a"));
    renderer::Box *fb = flex.boxForId(QStringLiteral("b"));
    QVERIFY(fa && fb);
    QCOMPARE(fa->width(), 150.0);
    QCOMPARE(fb->width(), 150.0);
    QCOMPARE(fb->x(), fa->x() + 150.0);
}

// --------------------------------------------------------------- positioning

void LayoutTest::movesRelativelyPositionedBoxes()
{
    // Relative positioning moves the box but leaves the space it would have
    // used reserved, which is the whole difference from absolute positioning.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='a' style='position:relative; left:30px; top:20px; width:100px; height:40px'>a</div>"
        "<div id='b' style='width:100px; height:40px'>b</div>"
        "</body></html>"));

    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    QVERIFY(a && b);

    QCOMPARE(a->x(), 30.0);
    QCOMPARE(a->y(), 20.0);

    // The following box is exactly where it would be if `a` had no offset, so
    // the displacement did not disturb the flow.
    QCOMPARE(b->y(), 40.0);

    // `right` moves the box the other way, and `bottom` moves it up.
    Page negated(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='a' style='position:relative; right:25px; bottom:10px; width:100px;"
        " height:40px'>a</div>"
        "</body></html>"));

    renderer::Box *negatedBox = negated.boxForId(QStringLiteral("a"));
    QVERIFY(negatedBox);
    QCOMPARE(negatedBox->x(), -25.0);
    QCOMPARE(negatedBox->y(), -10.0);
}

void LayoutTest::laysOutAbsolutelyPositionedBoxes()
{
    // An absolute box is placed against its positioned ancestor's padding box,
    // and takes no space in the flow around it.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='host' style='position:relative; width:400px; height:300px; margin-left:20px'>"
        "<div id='abs' style='position:absolute; left:50px; top:40px; width:100px; height:30px'>a</div>"
        "<div id='flow' style='height:60px'>f</div>"
        "</div></body></html>"));

    renderer::Box *host = page.boxForId(QStringLiteral("host"));
    renderer::Box *abs = page.boxForId(QStringLiteral("abs"));
    renderer::Box *flow = page.boxForId(QStringLiteral("flow"));
    QVERIFY(host && abs && flow);

    // The host's padding box starts at its border box, since it has no padding.
    QCOMPARE(abs->x(), host->x() + 50.0);
    QCOMPARE(abs->y(), host->y() + 40.0);

    // The in-flow sibling starts at the top: the absolute box took no space.
    QCOMPARE(flow->y(), host->y());
    // And the host's height is unaffected by the absolute box.
    QCOMPARE(host->height(), 300.0);
}

void LayoutTest::pinsAbsoluteBoxesToTheFarEdges()
{
    // `right` and `bottom` measure from the far edges of the containing block,
    // which is how a close button or a badge is placed.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='host' style='position:relative; width:400px; height:300px'>"
        "<div id='corner' style='position:absolute; right:10px; bottom:20px; width:80px;"
        " height:25px'>c</div>"
        "</div></body></html>"));

    renderer::Box *host = page.boxForId(QStringLiteral("host"));
    renderer::Box *corner = page.boxForId(QStringLiteral("corner"));
    QVERIFY(host && corner);

    QCOMPARE(corner->x(), host->x() + 400.0 - 80.0 - 10.0);
    QCOMPARE(corner->y(), host->y() + 300.0 - 25.0 - 20.0);
}

void LayoutTest::fillsBetweenOppositeOffsets()
{
    // `left: 0; right: 0` stretches the box across the containing block, which
    // is how an overlay or a full-width pinned bar is written.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='host' style='position:relative; width:400px; height:200px'>"
        "<div id='fill' style='position:absolute; left:20px; right:30px; top:10px; height:40px'>f</div>"
        "</div></body></html>"));

    renderer::Box *host = page.boxForId(QStringLiteral("host"));
    renderer::Box *fill = page.boxForId(QStringLiteral("fill"));
    QVERIFY(host && fill);

    QCOMPARE(fill->x(), host->x() + 20.0);
    QCOMPARE(fill->width(), 350.0); // 400 - 20 - 30
}

void LayoutTest::stretchesAnAbsoluteBoxBetweenTopAndBottom()
{
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='host' style='position:relative; width:300px; height:400px'>"
        "<div id='fill' style='position:absolute; top:50px; bottom:60px; left:0; width:100px'>f</div>"
        "</div></body></html>"));

    renderer::Box *fill = page.boxForId(QStringLiteral("fill"));
    QVERIFY(fill);
    QCOMPARE(fill->height(), 290.0); // 400 - 50 - 60
}

void LayoutTest::positionsAgainstTheNearestPositionedAncestor()
{
    // A nested absolute box is placed against the closest positioned ancestor,
    // not the outermost one and not the root.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='outer' style='position:relative; width:600px; height:400px'>"
        "<div id='middle' style='position:relative; margin-left:100px; margin-top:50px;"
        " width:300px; height:200px'>"
        "<div id='inner' style='position:absolute; left:10px; top:10px; width:50px;"
        " height:50px'>i</div>"
        "</div>"
        "</div></body></html>"));

    renderer::Box *middle = page.boxForId(QStringLiteral("middle"));
    renderer::Box *inner = page.boxForId(QStringLiteral("inner"));
    QVERIFY(middle && inner);

    // Measured from `middle`, not from `outer`.
    QCOMPARE(inner->x(), middle->x() + 10.0);
    QCOMPARE(inner->y(), middle->y() + 10.0);

    // An `absolute` box is itself a containing block for its own descendants,
    // even without a z-index, because it is positioned.
    Page nested(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='outer' style='position:relative; width:600px; height:400px'>"
        "<div id='abs' style='position:absolute; left:100px; top:100px; width:200px;"
        " height:100px'>"
        "<div id='child' style='position:absolute; left:5px; top:5px; width:20px;"
        " height:20px'>c</div>"
        "</div></div></body></html>"));

    renderer::Box *abs = nested.boxForId(QStringLiteral("abs"));
    renderer::Box *child = nested.boxForId(QStringLiteral("child"));
    QVERIFY(abs && child);
    QCOMPARE(child->x(), abs->x() + 5.0);
    QCOMPARE(child->y(), abs->y() + 5.0);
}

void LayoutTest::keepsOutOfFlowBoxesOutOfFlow()
{
    // An absolute box between two siblings must not move either of them, and
    // must not contribute to the document height.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='a' style='height:50px'>a</div>"
        "<div id='abs' style='position:absolute; top:0; left:0; width:100px; height:900px'>x</div>"
        "<div id='b' style='height:50px'>b</div>"
        "</body></html>"));

    renderer::Box *a = page.boxForId(QStringLiteral("a"));
    renderer::Box *b = page.boxForId(QStringLiteral("b"));
    QVERIFY(a && b);

    // The two in-flow boxes are adjacent, so the absolute box took no space.
    QCOMPARE(b->y(), a->y() + 50.0);
}

void LayoutTest::laysOutContentInsideAnAbsoluteBox()
{
    // The content of an absolute box has to be laid out like any other: an
    // earlier bug left its subtree unmeasured, so the box came out with no
    // height and its text painted at zero size.
    Page page(QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='host' style='position:relative; width:400px; height:200px'>"
        "<div id='abs' style='position:absolute; left:20px; top:20px; width:150px'>"
        "absolute text here</div>"
        "</div></body></html>"));

    renderer::Box *abs = page.boxForId(QStringLiteral("abs"));
    QVERIFY(abs);

    // The height comes from the content, and the text wrapped inside the width.
    QVERIFY2(abs->height() > 0, "the absolute box should have content height");
    QCOMPARE(abs->width(), 150.0);

    // Its text was measured, which is what the line boxes in the layout result
    // record. An earlier bug left the subtree unmeasured, so the box came out
    // with no height and the text painted at zero size.
    bool foundTextUnderIt = false;
    for (renderer::Box *line : page.result.lineBoxes) {
        for (const auto &child : line->children()) {
            if (!child->text().isEmpty() && child->width() > 0)
                foundTextUnderIt = true;
        }
    }
    QVERIFY2(foundTextUnderIt, "the absolute box's text should have been measured");

    // The text is positioned inside the absolute box, not at the page origin.
    const double firstLineY = [&] {
        for (renderer::Box *line : page.result.lineBoxes) {
            for (const auto &child : line->children()) {
                if (!child->text().isEmpty())
                    return child->y();
            }
        }
        return -1.0;
    }();
    QCOMPARE(firstLineY, abs->y());
}

void LayoutTest::paintsStickyBoxesAtTheViewportEdge()
{
    // Sticky positioning depends on the scroll position, which changes without a
    // re-layout, so it is resolved while painting. A sticky header must be at the
    // top of the viewport however far the page has been scrolled.
    Page page(QStringLiteral(
        "<html><head><style>"
        "#head{position:sticky; top:0; height:40px; background:#1f3a5f}"
        "#after{height:900px}"
        "</style></head><body style='margin:0'>"
        "<div id='head'></div><div id='after'></div>"
        "</body></html>"));

    renderer::Box *head = page.boxForId(QStringLiteral("head"));
    QVERIFY(head);
    // In the document the header is at the top, since sticky does not move it
    // until the page is scrolled.
    QCOMPARE(head->y(), 0.0);

    // The painted row of the header, found by looking for the dark background.
    const auto headerRow = [&](double scrollY) {
        renderer::Painter::Options options;
        options.scrollY = scrollY;
        options.viewportWidth = 400;
        options.viewportHeight = 300;
        const QImage image = renderer::Painter::renderToImage(page.boxTree.get(), 400, 300, options);
        for (int y = 0; y < 300; ++y) {
            const QRgb pixel = image.pixel(200, y);
            if (qBlue(pixel) > 80 && qRed(pixel) < 70 && qGreen(pixel) < 90)
                return y;
        }
        return -1;
    };

    QCOMPARE(headerRow(0), 0);
    // Scrolled down, a static box would have gone off the top; a sticky one is
    // still the first thing in the viewport.
    QCOMPARE(headerRow(200), 0);
    QCOMPARE(headerRow(500), 0);
}

void LayoutTest::paintsPositiveZIndexOnTop()
{
    // The scene: a red box in flow, then a blue box positioned over it. Both are
    // written in document order, so document order alone would paint blue last
    // and hide red. Giving red a positive z-index has to bring it back to the
    // front, which is what a dropdown or a modal relies on.
    const auto sampleColourAt = [](const QString &html, int x, int y) {
        Page page(html);
        const QImage image = renderer::Painter::renderToImage(page.boxTree.get(), 200, 120);
        return image.pixel(x, y);
    };

    const QString withoutZ = QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='red' style='position:absolute; left:0; top:0; width:100px; height:60px;"
        " background:#ff0000'></div>"
        "<div id='blue' style='position:absolute; left:0; top:0; width:100px; height:60px;"
        " background:#0000ff'></div>"
        "</body></html>");

    // Equal z-index keeps document order, so the later box wins.
    QCOMPARE(qBlue(sampleColourAt(withoutZ, 50, 30)), 255);

    const QString withZ = QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='red' style='position:absolute; z-index:5; left:0; top:0; width:100px;"
        " height:60px; background:#ff0000'></div>"
        "<div id='blue' style='position:absolute; left:0; top:0; width:100px; height:60px;"
        " background:#0000ff'></div>"
        "</body></html>");

    const QRgb pixel = sampleColourAt(withZ, 50, 30);
    QVERIFY2(qRed(pixel) > 200 && qBlue(pixel) < 60,
             qPrintable(QStringLiteral("expected red on top, got rgb(%1,%2,%3)")
                            .arg(qRed(pixel))
                            .arg(qGreen(pixel))
                            .arg(qBlue(pixel))));

    // Ordering between two positive levels follows the number, not the document.
    const QString stacked = QStringLiteral(
        "<html><body style='margin:0'>"
        "<div id='low' style='position:absolute; z-index:2; left:0; top:0; width:100px;"
        " height:60px; background:#00ff00'></div>"
        "<div id='high' style='position:absolute; z-index:9; left:0; top:0; width:100px;"
        " height:60px; background:#ff0000'></div>"
        "</body></html>");

    const QRgb top = sampleColourAt(stacked, 50, 30);
    QVERIFY2(qRed(top) > 200 && qGreen(top) < 60,
             qPrintable(QStringLiteral("the higher z-index should be on top")));
}

QTEST_MAIN(LayoutTest)
#include "tst_layout.moc"
