#pragma once

#include <QHash>
#include <QRectF>
#include <QSizeF>
#include <QString>

#include <memory>
#include <vector>

#include "css/Style.h"
#include "dom/Node.h"

namespace oqb::renderer {

/// A box in the formatting structure.
///
/// The box tree is the bridge between the DOM and layout: every element that
/// generates a box gets one, text runs become text boxes, and each box carries
/// the computed style that produced it together with the geometry layout gives
/// it. Anonymous boxes are inserted where the block and inline formatting rules
/// require one.
class Box
{
public:
    enum class Type {
        Block,     ///< display: block, list-item, table, flex, ...
        Inline,    ///< display: inline
        InlineBlock, ///< display: inline-block: inline outside, block inside
        Text,      ///< A run of text
        Replaced,  ///< Intrinsic-size content such as <img>
        Line,      ///< A line box, produced by inline layout
        Anonymous, ///< Inserted to hold inline content between blocks
        Bullet,    ///< The marker of a list item
    };

    Box(Type type, dom::Node *node, const css::ComputedStyle *style)
        : m_type(type)
        , m_node(node)
        , m_style(style)
    {
    }

    Type type() const { return m_type; }
    dom::Node *node() const { return m_node; }
    const css::ComputedStyle *style() const { return m_style; }
    void setStyle(const css::ComputedStyle *style) { m_style = style; }

    /// The element, when the box was generated by an element.
    dom::Element *element() const;

    // ----------------------------------------------------------- structure
    Box *parent() const { return m_parent; }
    const std::vector<std::unique_ptr<Box>> &children() const { return m_children; }

    Box *appendChild(std::unique_ptr<Box> child);
    /// Removes and destroys every child. Used by inline layout, which replaces
    /// the measured inline children with the line boxes built from them.
    void clearChildren() { m_children.clear(); }
    /// Detaches one child without destroying it, transferring ownership.
    std::unique_ptr<Box> detachChild(Box *child);
    Box *lastChild() const { return m_children.empty() ? nullptr : m_children.back().get(); }
    bool hasChildren() const { return !m_children.empty(); }
    int childCount() const { return static_cast<int>(m_children.size()); }
    Box *childAt(int index) const;

    /// The first child that is a block-level box, or nullptr.
    Box *firstBlockChild() const;

    /// The box's containing block: the nearest ancestor block-level box. Used
    /// to resolve percentage widths.
    Box *containingBlock() const;

    // ---------------------------------------------------------- geometry
    /// The border box, in the coordinate space of the nearest positioned
    /// ancestor (the document origin in practice).
    const QRectF &borderBox() const { return m_borderBox; }
    void setBorderBox(const QRectF &rect) { m_borderBox = rect; }

    /// The content box: inside padding and border.
    QRectF contentBox() const { return m_contentBox; }
    void setContentBox(const QRectF &rect) { m_contentBox = rect; }

    /// The padding box: inside the border.
    QRectF paddingBox() const;
    /// The margin box, used for margin collapsing and hit testing.
    QRectF marginBox() const;

    double x() const { return m_borderBox.x(); }
    double y() const { return m_borderBox.y(); }
    double width() const { return m_borderBox.width(); }
    double height() const { return m_borderBox.height(); }

    void setPosition(double x, double y) { m_borderBox.moveTo(x, y); }
    void setSize(double width, double height) { m_borderBox.setSize(QSizeF(width, height)); }

    /// Shifts this box and every descendant, used by relative positioning.
    void translate(double dx, double dy);

    // ------------------------------------------------------------- content
    const QString &text() const { return m_text; }
    void setText(const QString &text) { m_text = text; }

    /// For a Replaced box: the image or object URL.
    QString sourceUrl() const { return m_sourceUrl; }
    void setSourceUrl(const QString &url) { m_sourceUrl = url; }

    /// Intrinsic size of replaced content, resolved by the image loader.
    QSizeF intrinsicSize() const { return m_intrinsicSize; }
    void setIntrinsicSize(const QSizeF &size) { m_intrinsicSize = size; }

    /// The line boxes inside this box, valid after inline layout.
    const std::vector<Box *> &lines() const { return m_lines; }
    std::vector<Box *> &lines() { return m_lines; }

    /// True for a block-level box, i.e. one that stacks vertically.
    bool isBlockLevel() const
    {
        return m_type == Type::Block || m_type == Type::Anonymous || m_type == Type::Line;
    }
    bool isText() const { return m_type == Type::Text; }
    bool isReplaced() const { return m_type == Type::Replaced; }
    bool isInline() const
    {
        return m_type == Type::Inline || m_type == Type::InlineBlock || m_type == Type::Text
            || m_type == Type::Replaced || m_type == Type::Bullet;
    }

private:
    Type m_type;
    dom::Node *m_node = nullptr;
    const css::ComputedStyle *m_style = nullptr;

    Box *m_parent = nullptr;
    std::vector<std::unique_ptr<Box>> m_children;

    QRectF m_borderBox;
    QRectF m_contentBox;
    QString m_text;

    QString m_sourceUrl;
    QSizeF m_intrinsicSize;

    std::vector<Box *> m_lines;
};

/// Builds a box tree from a styled document.
///
/// Inline content that is not wrapped in a block is placed inside an anonymous
/// block box, exactly as CSS 2.2 section 9.2.1.1 requires, because layout needs
/// a single formatting context in which to place line boxes.
class BoxTreeBuilder
{
public:
    /// Builds the tree for `document`. The returned box owns the whole tree, so
    /// it must outlive any layout or paint pass.
    static std::unique_ptr<Box> build(dom::Document *document);

    /// The style engine used to look up computed styles. Must outlive the tree,
    /// because the boxes point directly at its entries.
    static void setStyleEngine(const css::StyleEngine *engine);

    /// Intrinsic sizes of replaced content, keyed by URL, so that an image which
    /// has already been decoded is given its real dimensions when the tree is
    /// built. Unlike the style engine this may be null, in which case replaced
    /// boxes fall back to their width and height attributes.
    static void setImageSizes(const QHash<QString, QSizeF> *sizes);

private:
    static std::unique_ptr<Box> buildForNode(dom::Node *node, const css::ComputedStyle *parentStyle);
    static bool isReplaced(const dom::Element *element);
};

} // namespace oqb::renderer
