#pragma once

#include <QDateTime>
#include <QString>

#include "network/HttpMessage.h"

namespace oqb::network {

/// What a stored response may be used for, decided from its own headers.
///
/// This is the freshness half of RFC 9111: a stored response is either fresh
/// enough to be used as it stands, stale and worth revalidating with the server,
/// or not storable at all. The arithmetic lives here rather than inside
/// `ResourceLoader` because it is the part that is easy to get subtly wrong and
/// the part that can be tested without a socket.
///
/// The directives are read from `Cache-Control` where present, because a header
/// is explicit and a heuristic is not. `Expires` is the fallback for a response
/// that predates `Cache-Control`, and the `Last-Modified` heuristic is the last
/// resort, as the specification allows.
class CachePolicy
{
public:
    /// How a response told the cache to treat it.
    enum class Storability {
        /// May be stored and reused while fresh.
        Storable,
        /// May be stored, but must be revalidated before every reuse.
        MustRevalidate,
        /// Must not be stored at all.
        NotStorable,
    };

    /// The directives this browser understands, as read from one response.
    struct Directives
    {
        bool noStore = false;
        bool noCache = false;
        bool mustRevalidate = false;
        bool isPublic = false;
        bool isPrivate = false;
        /// `max-age`, or -1 when absent. `s-maxage` applies to shared caches, so
        /// it is deliberately ignored: this cache serves one user.
        int maxAgeSeconds = -1;
    };

    /// Reads `Cache-Control` and, for the fields `Cache-Control` did not set,
    /// `Expires`.
    static Directives parse(const HeaderList &headers);

    /// True when the response may be written to the cache at all.
    ///
    /// A response is refused when it says `no-store` (or its request did, which
    /// the caller passes in through `requestDirectives`), and when the method
    /// was not one whose result is safely reusable. A `Set-Cookie` response is
    /// still storable: the cookie is absorbed separately, and refusing to cache
    /// would make every logged-in page re-download on every visit.
    static bool isStorable(const Directives &directives, int statusCode);

    /// The freshness lifetime in seconds: how long the response stays usable
    /// without asking the server. 0 means "always revalidate".
    ///
    /// `date` and `lastModified` are the parsed header values, passed in rather
    /// than read again so the arithmetic is a pure function of its inputs.
    static int freshnessLifetime(const Directives &directives,
                                 const QDateTime &date,
                                 const QDateTime &expires,
                                 const QDateTime &lastModified);

    /// Parses an HTTP date, accepting the three forms RFC 9110 requires.
    ///
    /// An unparseable date returns an invalid `QDateTime`, which callers treat as
    /// "the server did not say" rather than as the epoch. Reading a malformed
    /// `Expires` as 1970 would make a response instantly stale, which is safe but
    /// wrong: the specification says to ignore a value that cannot be parsed.
    static QDateTime parseHttpDate(const QString &value);

    /// Formats a date the way a request header must carry it (IMF-fixdate).
    static QString formatHttpDate(const QDateTime &date);

    /// True when `vary` is a header this cache can ignore.
    ///
    /// A response that varies by a header the cache does not key on must not be
    /// stored: serving a variant to a request that did not ask for it is the bug
    /// `Vary` exists to prevent. `Accept-Encoding` is safe to ignore here because
    /// this browser sends exactly one value and never changes it.
    static bool varyIsHarmless(const QString &vary);

    /// The age of a stored response in seconds: how long ago it was generated by
    /// the origin, not how long ago it was received.
    ///
    /// A response can be old when it arrives - a proxy may have held it - so the
    /// `Date` header contributes. RFC 9111 section 4.2.3. The parameters are
    /// passed explicitly rather than as a struct so this header stays free of any
    /// dependency on `Resource`.
    static qint64 ageSeconds(const QDateTime &storedAt, const QDateTime &date,
                             const QDateTime &now);

    /// True when a stored response may be served without contacting the server.
    ///
    /// The entry's lifetime and its `no-cache` flag are the caller's to supply,
    /// since they come from the response this policy parsed.
    static bool isFresh(qint64 ageSeconds, int freshnessLifetimeSeconds, bool noCache);
};

} // namespace oqb::network
